[package]
name = "day12"
version = "0.1.0"
authors = ["Naman Wahi <naman@nplan.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
maplit = "1.0.2"
ndarray = "0.14.0"